name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build Release Assets
        run: |
          chmod +x package-release.sh
          ./package-release.sh

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: ${{ github.ref_name }}
          files: |
            dist/surge-sub-converter-linux-amd64.tar.gz
            dist/surge-sub-converter-linux-arm64.tar.gz
          generate_release_notes: true
          draft: false
          prerelease: false
